export const SORT_SONGS_ASCENDING = "SORT_SONGS_ASCENDING";
export const SORT_SONGS_DESCENDING = "SORT_SONGS_DESCENDING";
export const GET_INITIAL_SONGS = "GET_INITIAL_SONGS";
export const SET_API_LOADING = "SET_API_LOADING";
export const ADD_TO_STORAGE = "ADD_TO_STORAGE";
export const CLEAR_STORAGE = "CLEAR_STORAGE";

