export const SORT_SONGS_ASCENDING = "SORT_SONGS_ASCENDING";
export const SORT_SONGS_DESCENDING = "SORT_SONGS_DESCENDING";
export const GET_INITIAL_SONGS = "GET_INITIAL_SONGS";
export const SET_API_LOADING = "SET_API_LOADING";
export const GET_INITIAL_IMAGES = "GET_INITIAL_IMAGES";
export const SET_CURRENT_IMAGE = "SET_CURRENT_IMAGE";
export const SET_IMAGES_LOADING = "SET_IMAGES_LOADING";

